# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1huMO8HmSo0A3VIgofTiY2cW69r2W7PwT
"""

import pandas as pd
import altair as alt

# cargar datos
df = pd.read_csv("/content/teleseries_database_limpia.csv", sep=";")

# Echar un vistazo
df.head(29)